[package]
name = "avail-rust-ffi"
description = "FFI Avail Rust SDK"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
avail-rust = { package = "avail-rust-client", version = "0.4.0-rc.1", default-features = false, features = ["native", "reqwest"] }
libc = "0.2"
tokio = "1.47"
