[workspace]

[package]
name = "avail-rust"
edition = "2021"
version = "0.2.0"
license = "ISC"

exclude = [
    "build_api.sh",
    "build_sdk.sh",
    "install_dependencies.sh",
    "justfile",
    "scripts/*",
    "changelog",
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1.42.0", default-features = false, features = ["sync"] }
serde = { version = "1.0.195", default-features = false, features = ["derive" ] }
serde_json = { version = "1.0.124", default-features = false, features = ["raw_value"] }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "bit-vec"] }
impl-serde = { version = "0.5.0", default-features = false }
hex = { version = "0.4", default-features = false }
base58 = { version = "0.2.0", default-features = false }
bounded-collections = { version = "0.2.0", default-features = false, features = ["serde"] }
primitive-types = { version = "0.13.1", default-features = false }
log = { version = "0.4.22", default-features = false }
env_logger = { version = "0.11.5", default-features = false, features = ["humantime", "auto-color" ] }

# Scale
scale-info = { version = "2.11.6", default-features = false, features = ["bit-vec"] }
scale-decode = { version = "0.16.0", default-features = false }
scale-encode = { version = "0.10.0", default-features = false }

frame-metadata = {  version = "20.0.0", default-features = false }
frame-decode = { version = "0.7.1", default-features = false }

subxt-core = { version = "0.41.0", default-features = false }
subxt-signer = { version = "0.41.0", default-features = false, features = ["sr25519", "subxt"] }
subxt-rpcs = { version = "0.41.0", default-features = false }
reqwest = { version = "0.12.15", default-features = false, features = ["json"] }
thiserror = { version = "2.0.12", default-features = false }

# Enabled with Subxt
subxt = { version = "0.41.0", default-features = false, optional = true  }

# Enabled with Wasm
wasm-bindgen-futures = { version =  "0.4.43", optional = true  }
wasmtimer = { version = "0.4.1", optional = true }

[features]
default = [ "native" ]
subxt_metadata = []
subxt = [
	"dep:subxt",
]
native = [
	"subxt?/native",
	"subxt-core/std",
	"subxt-signer/std",
	"subxt-rpcs/native",
]
wasm = [
	"subxt?/web",
	"subxt-signer/web",
	"subxt-rpcs/web",
	"wasmtimer",
	"wasm-bindgen-futures",
]
