[workspace]

[package]
name = "avail-rust"
edition = "2021"
version = "0.1.9"
license = "ISC"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = { version = "1", default-features = false, features = ["from", "constructor"] }
tokio = { version = "1.42.0", default-features = false }
subxt = { version = "0.41.0", default-features = false }
subxt-core = { version = "0.41.0", default-features = false  }
subxt-signer = { version = "0.41.0", default-features = false }
subxt-rpcs = { version = "0.41.0", default-features = false }
serde = { version = "1.0.195", features = ["derive", ] }
serde_json = { version = "1.0.124", features = ["raw_value"] }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
	"full",
	"bit-vec",
] }
impl-serde = { version = "0.4.0", default-features = false }
scale-info = { version = "2.5.0", features = ["bit-vec"] }
hex = { version = "0.4" }
base58 = { version = "0.2.0" }
bounded-collections = { version = "0.2.0", features = ["serde"] }
primitive-types = { version = "0.13.1", default-features = false }
log = { version = "0.4.22", default-features = false }
env_logger = { version = "0.11.5" }

reqwest = { version = "0.12.15", default-features = false, features = ["json"] }
hyper = { version = "1.6.0", default-features = false, features = ["http1", "client"] }
hyper-util = { version = "0.1.0", default-features = false }
http-body-util = { version = "0.1.3", default-features = false }
wasm-bindgen-futures = "0.4.43"

[features]
default = [ "native" ]
native = [
	"derive_more/std",
	"subxt/default",
	"subxt-core/std",
	"subxt-signer/default",
]
wasm = [
	"subxt/web",
	"subxt-signer/web",
	"subxt-signer/sr25519",
	"subxt-signer/subxt",
]
