[workspace]

[package]
name = "storage-example"
edition = "2024"

[dependencies]
avail-rust-client = { path = "./../../client", default-features = false, features = ["native", "reqwest", "subxt", "tracing" ] }
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros"] }