[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which team is The Best Team?"
prompt.distractors = [
  "The Node Team",
  "Devops Team",
]
answer.answer = "HR Team"
context = """
Sike, it's actually The Node Team.
"""
id = "dad95694-d3fb-4f00-ae61-71c4cfeb66c3"
