[workspace]

[package]
name = "sdk-examples"
edition = "2021"
default-run = "sdk-examples"


[dependencies]
avail-rust = { path = "../." }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
anyhow = { version = "1.0.98" }